stages:
  - test
  - deploy

test:
  image: node:13-alpine
  stage: test
  environment:
    name: test
  script:
    - apk add --no-cache python3 make g++
    - npm install -g @angular/cli
    - npm ci
    - ng build

deploy:
  image: node:13-alpine
  stage: deploy
  environment:
    name: test
  script:
    - apk add --no-cache python3 make g++
    - npm install -g @angular/cli
    - npm install -g firebase-tools
    - npm ci
    - ng build
    - firebase --project phaenonet --token "$FIREBASE_TOKEN" deploy
  only:
    - master
