stages:
  - test
  - deploy

test:
  image: node:13-alpine
  stage: test
  environment:
    name: test
  script:
    - apk add --no-cache python3 make g++
    - npm ci
    - npx ng build

deploy-phaenonet-test:
  image: node:13-alpine
  stage: deploy
  environment:
    name: test
  script:
    - apk add --no-cache python3 make g++
    - npm ci
    - npx ng build
    - npx firebase --project phaenonet-test --token "$FIREBASE_TOKEN" deploy
  only:
    - master

deploy-phaenonet:
  image: node:13-alpine
  stage: deploy
  environment:
    name: test
  script:
    - apk add --no-cache python3 make g++
    - npm ci
    - npx ng build --prod
    - npx firebase --project phaenonet --token "$FIREBASE_TOKEN" deploy
  only:
    - master
  when: manual
