version: "2"
services:
  phaenonet-app:
    build: .
    ports:
      - 4200:4200
  e2e-test:
    depends_on:
      - phaenonet-app
    image: globeswiss/codeceptjs-playwright
    volumes:
       - "${PWD}/e2e:/tests:rw"
    entrypoint: [
      'wait-for-it', 'phaenonet-app:4200', '-t', '120', '--', 
      'npx', 'codeceptjs']
    command: [
      'run', 
      '--override', '{ "helpers": { "Playwright": { "url": "http://phaenonet-app:4200" }}}', 
      "--reporter", "mochawesome",
      "--grep", "Individual View"]
    stdin_open: false
    tty: false
