version: "3"
services:
  phaenonet-app:
    build: .
    ports:
      - 4200:4200
  e2e-test:
    depends_on:
      - phaenonet-app
    image: globeswiss/codeceptjs-playwright
    volumes: 
       - "${PWD}:/tests:rw"
    entrypoint: ['wait-for-it', 'phaenonet-app:4200', '-t', '30', '--', 'npx', 'codeceptjs']
    command: ['run', '--override', '{"helpers":{"Playwright":{"url":"http://phaenonet-app:4200"}}}', '--grep', 'test quantil regression on 2018']
