version: '2'
services:
  phaenonet-app:
    build: .
    ports:
      - 4200:4200
  e2e-test:
    depends_on:
      - phaenonet-app
    build: ./e2e
    volumes:
      - './e2e/output:/tests/output:rw'
