name: 'deploy-hosting action'
description: 'deploys firebase hosting'
inputs:
  workload_identity_provider:
    description: 'The workload identity provider'
    required: true
  service_account:
    description: 'The gcp service account'
    required: true
  repo_token:
    description: 'Github token for commenting on PR, needs permission: pull-request: write'
    required: false
  project_id:
    description: 'The Firebase project id'
    required: true
  entry_point:
    description: 'The folder firebase.json is located in'
    default: .
  channel_id:
    description: 'Channel name or live for live deployment'
    required: false
  expires:
    description: 'Channel expires'
    required: false
  node_version:
    description: 'Node version to use'
    required: true

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v6.0.0
      with:
        node-version: ${{ inputs.node_version }}
    - name: Install Firebase CLI
      shell: bash
      run: npm install -g firebase-tools
    - id: auth
      name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v3.0.0
      with:
        workload_identity_provider: ${{ inputs.workload_identity_provider }}
        service_account: ${{ inputs.service_account }}
    - name: Deploy to Firebase Hosting
      shell: bash
      run: |
        if [ -n "${CHANNEL_ID}" ] && [ "${CHANNEL_ID}" != "live" ]; then
          firebase hosting:channel:deploy "${CHANNEL_ID}" \
            --project "${PROJECT_ID}" \
            --expires "${EXPIRES:-7d}"
        else
          firebase deploy --only hosting --project "${PROJECT_ID}"
        fi
      working-directory: ${{ inputs.entry_point }}
      env:
        CHANNEL_ID: ${{ inputs.channel_id }}
        PROJECT_ID: ${{ inputs.project_id }}
        EXPIRES: ${{ inputs.expires }}
