name: 'angular-http-server action'
description: 'start angular-http-server'
inputs:
  port:
    description: 'The port to listen on'
    required: true
  path:
    description: 'The path to serve from'
    required: true
runs:
  using: 'composite'
  steps:
    - run: pnpm dlx angular-http-server --path ${INPUTS_PATH} --p ${INPUTS_PORT} &
      shell: bash
      env:
        INPUTS_PATH: ${{ inputs.path }}
        INPUTS_PORT: ${{ inputs.port }}
    - name: Wait on
      uses: iFaxity/wait-on-action@v1.2.1
      with:
        resource: http://localhost:${{ inputs.port }}
