name: 'angular-http-server action'
description: 'start angular-http-server'
inputs:
  port:
    description: 'The port to listen on'
    required: true
  path:
    description: 'The path to serve from'
    required: true
  node_version:
    description: 'Node version to use. default: latest'
    default: latest
  pnpm_version:
    description: 'PNPM version to use. default: latest'
    default: 'latest'
runs:
  using: 'composite'
  steps:
    - uses: pnpm/action-setup@v3
      with:
        version: ${{ inputs.pnpm_version }}
    - uses: actions/setup-node@v4.0.1
      with:
        node-version: ${{ inputs.node_version }}
        cache: 'pnpm'
    - run: pnpm dlx angular-http-server --path ${{ inputs.path }} --p ${{ inputs.port }} &
      shell: bash
    - name: Wait on
      uses: iFaxity/wait-on-action@v1.1.0
      with:
        resource: http://localhost:${{ inputs.port }}
