project phaenonet {
  database_type: 'Firestore'
  Note: '''
    # PhaenoNet Data
    Description of PhaenoNet data structures.
  '''
}

enum locale {
  "de-CH"
  "fr-CH"
  "it-CH"
}

enum source {
  globe
  meteoswiss
  ranger
  wld
}

table activities {
  id string [pk]
  action activity_action
  activity_date date
  followers array[string]
  individual_id string [ref: > individuals.id]
  individual_name string
  observation_id string [ref: > observations.id]
  phenophase string [note: 'definitions/config_static/phenophases']
  phenophase_name string
  source source
  species string [note: 'definitions/config_static/species']
  species_name string
  type individual_type
  user string [ref: > users.id]
  user_name string

  indexes {
    (followers, activity_date) //[note: 'followers Arrays, activity_date Descending']
  }

  note: 'Activities (observations) tracked by users.'
}

ref activity_followers: activities.followers <> users.id

enum activity_action {
  create
  delete
  modify
}

tablegroup anaytics {
  analytics_state
  analytics_results
}

table analytics_results {
  id string [pk, note: 'year_species_source[_altitudegroup]']
  source source
  species string
  type analytics_type
  values map [note: 'map of statistic values per phenophase']
  year number

  note: 'Statistical values displayed in the statistics section in the Phaenonet application.'
}

table analytics_state {
  id string [pk, note: 'year_species_source[_altitudegroup]']
  source source
  species string [note: 'definitions/config_static/species']
  state map [note: 'map of observation_date per phenophase']
  year number

  note: 'Internal data-structure for calculating statistical values.'
}


enum analytics_type {
  species
  altitude
}

table definitions {
  id string [pk]
  note: 'Applications specific definitions and states.'
}


table maps {
  id string [pk, note: 'id is year, the attributes are stored in a map for each individual (data.<individual_id>)']
  g map [note: 'see individuals.geopos']
  p string [note: 'see indivduals.last_phenophase']
  so string [note: 'see individuals.source']
  sp string [null, note: 'see individuals.species']
  ss array[string] [null, note: 'see individuals.station_species']
  t string [note: 'see individuals.type']

  note: '''
    Contains one document per year containing all individual information needed to display on the map.
    The attributes are wrapped in a field "data" which needs to be extempted from single field index creation due to the size of the document.
  '''
}

table individuals {
  id string [pk, note: 'year_individual']
  altitude number
  description string [note: 'definitions/config_static/description']
  exposition string [note: 'definitions/config_static/exposition']
  forest string [note: 'definitions/config_static/forest']
  geopos map [note: 'map containing lng, lat']
  gradient number
  habitat string [note: 'definitions/config_static/habitat']
  individual string
  last_observation_date date [null]
  last_phenophase string [note: 'definitions/config_static/phenophases']
  less100 string [note: 'definitions/config_static/less100']
  name string
  shade string [note: 'definitions/config_static/shade']
  source source
  species string [note: 'definitions/config_static/species']
  station_species array[string] [note: 'definitions/config_static/species']
  type individual_type
  user string [ref: < users.id]
  watering string [note: 'definitions/config_static/watering']
  year number
  created timestamp
  modified timestamp

  indexes {
    (year, last_observation_date) //[note: 'year Ascending last_observation_date, Descending']
    (user, modified) //[note: 'user Ascending, modified Descending']
  }

  note: 'Definitions of (single) individuals and phenological stations.'
}

enum individual_type {
  individual
  station
}

table observations {
  id string [note: 'ids have different patterns depending on the source']
  date date
  individual string
  individual_id string [ref: > individuals.id]
  tree_id string [null, note: 'optional tree id/name within a station (currently only on wld source)']
  phenophase string [note: 'definitions/config_static/phenophases']
  source source
  species string [note: 'definitions/config_static/species']
  user string [ref: > users.id]
  year number
  created timestamp
  modified timestamp

  note: 'Observed phenological phases for individuals and stations.'
}

ref observations_individuals: observations.individual <> individuals.individual

table nicknames {
  id string [pk, ref: - users.nickname]
  user string [unique, ref: - users.id]

  note: 'Public nickname list.'
}

table public_user {
  id string [pk, ref: - users.id]
  nickname string [unique, ref: - users.nickname]
  roles array[roles] [note: 'defined roles: ranger']

  note: 'Public user information.'
}

table users {
  id string [pk]
  nickname string [unique]
  locale locale
  firstname string [null]
  lastname string [null]
  following_individuals array[string] [null]
  following_users array[string] [null]
  created timestamp
  modified timestamp

  note: 'Private user information.'
}

ref following_individuals: users.following_individuals <> individuals.individual
ref following_users: users.following_users <> users.id

tablegroup users {
  nicknames
  public_user
  users
}

table invites {
  id string [pk]
  email string
  locale locale
  user string [ref: > users.id]
  sent timestamp [null]
  numsent number [null]
  register_date timestamp [null]
  register_nick string [null]
  register_user string [null, ref: > users.id]
  created timestamp
  modified timestamp

  note: 'User invites.'
}

table invites_lookup {
  id string [pk, ref: > invites.email]
  invites array[string]

  note: 'Reverse lookup table for finding the invite initiator(s).'
}

ref invites_users: invites_lookup.invites <> users.id

tablegroup invites {
  invites
  invites_lookup
}

table sensors {
  id string [pk, note: 'id is <year>_<individual_id>, the attributes are stored for each day in the path data.<date>']
  ahs number [note: 'air humidity sum']
  ats number [note: 'air temperature sum']
  shs number [note: 'soil humidity sum']
  sts number [note: 'soil temperature sum']
  n number [note: 'number of data points forming the sums']

  note: '''
    Contains daily aggregated iot sensor data for individuals on Phaenonet+.
    The attributes are wrapped in a field "data" which needs to be extempted from single field index creation due to the size of the document.
  '''
}
