# Build PRs to master

name: Build PR

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ build_pr ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Install Dependencies
        run: | 
          npm install @angular/cli --no-save
          npm ci --unsafe-perm
      - name: Build
        run: npx ng build
      - name: Archive PR Artifact
        uses: actions/upload-artifact@master
        with:
          name: dist-pr-build
          path: dist
