name: Test

on:
  pull_request:
    branches: [master]
  push:
    branches: [master, test-pr]

env:
  NODE_VERSION: '14'
  CACHE_SEQ: 1

jobs:
  cache-deps:
    name: Cache Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3.3.0
      - uses: actions/setup-node@v3.6.0
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Cache dependencies
        # check options to skip download in future versions
        id: cache
        uses: actions/cache@v3.2.2
        with:
          path: ./node_modules
          key: module-${{ env.NODE_VERSION }}-${{ env.CACHE_SEQ }}-${{ hashFiles('package-lock.json') }}
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci --also=dev
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: cache-deps
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3.3.0
      - uses: actions/setup-node@v3.6.0
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3.2.2
        with:
          path: ./node_modules
          key: module-${{ env.NODE_VERSION }}-${{ env.CACHE_SEQ }}-${{ hashFiles('package-lock.json') }}
      - name: Set API info
        uses: wei/wget@v1.1.1
        with:
          args: -q -P ./src/local/ ${{ secrets.FIREBASE_TEST_API_URL }}
      - name: Build test version
        run: npx ng build -c local
      - name: Archive Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: dist-pr-build
          path: dist
  test:
    # workaround fixed by https://github.com/dorny/test-reporter/pull/174
    permissions:
      statuses: write
      checks: write
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: cache-deps
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3.3.0
      - uses: actions/setup-node@v3.6.0
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3.2.2
        with:
          path: ./node_modules
          key: module-${{ env.NODE_VERSION }}-${{ env.CACHE_SEQ }}-${{ hashFiles('package-lock.json') }}
      - name: Build test version
        run: npx ng test
        env:
          JEST_JUNIT_OUTPUT_DIR: reports
      - name: Test Report
        uses: dorny/test-reporter@v1.6.0
        with:
          name: Unit Tests Results
          path: reports/junit.xml
          reporter: jest-junit
        if: always()
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3.1.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: reports/lcov.info
          flags: unittests
        if: always() && github.actor != 'dependabot[bot]' && github.actor != 'dependabot-preview[bot]'
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1.3.0
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: reports/lcov.info
        if: always() && github.actor != 'dependabot[bot]' && github.actor != 'dependabot-preview[bot]'
  e2e-tests:
    concurrency: e2e-test
    name: E2E-tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3.3.0
      - uses: actions/setup-node@v3.6.0
        with:
          node-version: ${{ env.NODE_VERSION }}
      - uses: actions/download-artifact@v3.0.2
        with:
          name: dist-pr-build
      - name: Start server
        uses: ./.github/actions/angular-http-server-action
        with:
          path: ./phaenonet
          port: 4200
      - name: setup codeceptjs
        working-directory: e2e
        run: npm i
      - name: e2e-test
        working-directory: e2e
        run: npx codeceptjs run --reporter mochawesome
      - uses: actions/upload-artifact@v3.1.2
        with:
          name: e2e-test-report
          path: e2e/output
        if: ${{ always() }}
  codacy:
    name: Codacy Checks
    runs-on: ubuntu-latest
    needs: cache-deps
    if: github.actor != 'dependabot[bot]' && github.actor != 'dependabot-preview[bot]'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3.3.0
      - uses: actions/setup-node@v3.6.0
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3.2.2
        with:
          path: ./node_modules
          key: module-${{ env.NODE_VERSION }}-${{ env.CACHE_SEQ }}-${{ hashFiles('package-lock.json') }}
      - name: Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@v4.2.0
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          upload: true
          verbose: true
          parallel: 10
  checks:
    name: run checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3.3.0
      - uses: actions/setup-node@v3.6.0
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install Dependencies
        run: npm ci --include=dev --ignore-scripts
      - name: check style
        run: npx prettier -c "."
      - name: check map icon completeness
        run: |
          diff <(ls src/assets/img/map_pins/de-CH) <(ls src/assets/img/map_pins/fr-CH) || exit
          diff <(ls src/assets/img/map_pins/de-CH) <(ls src/assets/img/map_pins/it-CH) || exit
