# Test build and deploy workflow

name: CI Build and Deploy Test

on:
  push:
    branches: [ master ]

jobs:
  build-test:
    name: Build Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npx ng build
      - name: Archive Test Artifact
        uses: actions/upload-artifact@master
        with:
          name: dist-test
          path: dist
  deploy-test:
    name: Deploy Test
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dist-test
          path: dist/phaenonet
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --project phaenonet-test
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
